### ISSUE TITLE
Bug report for Open Vision 12.2

### ISSUE THREAD

**Issue by fairbird** [OpenVisionE2/reports#1]
**Open Vision revision**
Tell us it's OV 12.2-rX?

**STB name**
DM920

You have two issues on your images as well as on my images .. Same issues
But on OpenATV images no problem at all

1- alphatest for skins if using (blend) no problem but If using (on) then get issue as like screenshot shown
OpenVision
![1](https://github.com/OpenVisionE2/reports/assets/1761779/92b2ed4a-abfc-4e12-9df8-0efe9af363cf)
OpenATV
![2](https://github.com/OpenVisionE2/reports/assets/1761779/4f50c2d9-1e42-4fa5-a215-14e2157b2f5b)
......
1- LCD doesn't work well .. Picon not set in center, Take some left side. And top of lcd not clear ..
OpenVision
![4](https://github.com/OpenVisionE2/reports/assets/1761779/ece0e0e9-5a7e-4dbf-94e8-3e64d13cc51a)
OpenATV
![3](https://github.com/OpenVisionE2/reports/assets/1761779/f8e3718f-fe2c-4628-b9e7-9dd994dc55de)

**Comment by norhap** [comment]
@fairbird https://github.com/norhap/enigma2-openvision-1/commit/8c5edb4abfcfc5119e27f5ed152b0da583318e82

**Comment by fairbird** [comment]
After testing on my source (alphatest="blend") work fine ...
https://github.com/fairbird/enigma2-dreambox/commit/94d813f5c4ad4612ddaff713e3beff56a44769f8

Now we need to fix lcd ...

**Comment by fairbird** [comment]
@norhap 
After that comment, I don't see any difference between (alphatest="blend") and (alphatest="on") in behavior of ePixmap ..
On OpenaTV if I use (alphatest="on") I see plugin screens opening faster than with (alphatest="blend") around 1 and half second.
But on my image no difference same time ...
Did you build new openvision for dm920 >> I need to test it also !!

**Comment by persianpros** [comment]
You should check https://images.openvision.dedyn.io we're compiling 13.1 for all.

**Comment by fairbird** [comment]
@norhap

I have fix my source with those two commits. No more issues with alphatest (blend or on) And also more fast more stable with high resolution depth of skins graphics.
And also Solved LCD panel. No more problem ..

https://github.com/fairbird/enigma2-dreambox/commit/8d66188835ea9986960005a7f6ff212d45200392
https://github.com/fairbird/enigma2-dreambox/commit/8fa3a1d5f8a5c7a5847ec097b237892e231ff8fc
