### ISSUE TITLE
dm8000 crash

### ISSUE THREAD

**Issue by Leeawa12** [OpenVisionE2/reports#12]
dm8000 crash

**Comment by persianpros** [comment]
How do you trigger this bug? Please walk us through it step by step.

Also we need the output of:

`init 4&& sleep 5&& ENIGMA_DEBUG_LVL=4 enigma2`

**Comment by Leeawa12** [comment]
I don't know what is required of me now
Note that I use Google for translation

**Comment by Leeawa12** [comment]
I tried for the 3rd time same problem
![٢٠٢٣٠٦١٥_١٧٤٠٠٣](https://github.com/OpenVisionE2/reports/assets/136477333/1c40337d-55eb-4474-8239-0fa942d934c4)
![٢٠٢٣٠٦١٥_١٧٤٠١٩](https://github.com/OpenVisionE2/reports/assets/136477333/258f3078-7f4d-40ec-8b26-2f706a525cf6)
![٢٠٢٣٠٦١٥_١٧٤٠٤٥](https://github.com/OpenVisionE2/reports/assets/136477333/6a2733a9-5130-4910-adbf-f723ccdcec71)
[enigma2_crash_2023-06-15_17-40-12.log](https://github.com/OpenVisionE2/reports/files/11759566/enigma2_crash_2023-06-15_17-40-12.log)

**Comment by persianpros** [comment]
If network (LAN) is working connect to your box via telnet like

telnet 192.168.1.2 (your dm8000's ip)
root
init 4&& sleep 5&& ENIGMA_DEBUG_LVL=4 enigma2

and show us the logs.

**Comment by persianpros** [comment]
We don't need a file, we need you to run this command:

`init 4&& sleep 5&& ENIGMA_DEBUG_LVL=4 enigma2`

and show us the output.

**Comment by Leeawa12** [comment]
Do you wait 60 minutes
![EEEEEEEEEEEEEEEEEEE](https://github.com/OpenVisionE2/reports/assets/136477333/96e24d2c-0bf5-4c16-9496-8f57d75bd8c8)

**Comment by Leeawa12** [comment]
![IMG_0004](https://github.com/OpenVisionE2/reports/assets/136477333/ce918e35-91cd-4026-87b9-fa578bf12154)

**Comment by Leeawa12** [comment]
What do I do now

**Comment by Leeawa12** [comment]
I am still waiting for my problem to be resolved. Thank you

**Comment by Leeawa12** [comment]
[enigma2_crash_2023-06-18_13-36-42.log](https://github.com/OpenVisionE2/reports/files/11781224/enigma2_crash_2023-06-18_13-36-42.log)

**Comment by WXbet** [comment]
okay, now we have got the crash and can investigate:
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:36:42.5992   File "/home/abcde/env/New-1/openvision/build/tmp/work/dm8000-oe-linux/enigma2/develop+gitAUTOINC+7f713ec28b-r0/image/usr/lib/enigma2/python/Screens/ScanSetup.py", line 626, in __init__
13:36:42.6048   File "/home/abcde/env/New-1/openvision/build/tmp/work/dm8000-oe-linux/enigma2/develop+gitAUTOINC+7f713ec28b-r0/image/usr/lib/enigma2/python/Screens/ScanSetup.py", line 1026, in createConfig
13:36:42.6101   File "/home/abcde/env/New-1/openvision/build/tmp/work/dm8000-oe-linux/enigma2/develop+gitAUTOINC+7f713ec28b-r0/image/usr/lib/enigma2/python/Screens/ScanSetup.py", line 1026, in <listcomp>
13:36:42.6157 TypeError: 'NoneType' object is not subscriptable
``` 

@persianpros , @norhap  Any idea what causes the problem?

**Comment by Leeawa12** [comment]
Thank you very much
What should I do now.. I am a fan of a picture openvision

**Comment by Leeawa12** [comment]
What should I do now..
Please Help

**Comment by norhap** [comment]
[ScanSetup.zip](https://github.com/OpenVisionE2/reports/files/11805801/ScanSetup.zip)
unzip this zip.
the file ScanSetup.py put it in this path:
/usr/lib/enigma2/python/Screens/
restart enigma2

**Comment by Leeawa12** [comment]
**Are you making fun of me?
Same problem...I'm going to change the picture**


![1](https://github.com/OpenVisionE2/reports/assets/136477333/5676a451-e5e2-4b10-8889-f1393c4706c1)
[enigma2_crash_2023-06-20_23-16-26.log](https://github.com/OpenVisionE2/reports/files/11806267/enigma2_crash_2023-06-20_23-16-26.log)

**Comment by Leeawa12** [comment]
The image needs a new build

**Comment by norhap** [comment]
I offer you a test, and I have wasted my time to modify the code, what are you saying about making fun of you? you have very little education

**Comment by Leeawa12** [comment]
Five days I wait... and in the end you give me a file that doesn't work and says where is the irony

Do your work well before you hurt something that doesn't work

**Comment by norhap** [comment]
You are ignorant, you have no idea who modified the code, you upload a log that does not say anything, you use a program from the years of Christ for FTP and you get tired of waiting, or that you paid me or me with money for it to the rest of the team.

**Comment by persianpros** [comment]
@norhap 

Forget about him, some poeple have no idea what development is.

@Leeawa12 

We're not paid developers and it's not our duty to hold our lives or other projects to work on your problem specifically.

dm8000 is an old hardware which is still supported in OV, the file norhap gave you was for test so doesn't mean it will fix the problem immieadetly.

For fixing something in a box like dm8000 (which we don't have in our team) time is a great deal as it may take a month to fix a problem with lots of tests. When you don't have any idea how development works it's better to leave it.

We support more than 350 models and it's a normal thing to see bugs on old hardwares as we don't have them.

Your native language is not English so you may not understand us well but feel free to use other images.

**Comment by Leeawa12** [comment]
![2](https://github.com/OpenVisionE2/reports/assets/136477333/fb2a79d2-0d64-4672-ae69-c984dda9771e)

**I am madly in love with the Dream 8000 and own the Dream 2**

I am very sorry..I was in a state of anger and I repeat my apologies

**Comment by persianpros** [comment]
Try this test image: https://images.openvision.dedyn.io/13.1/.Test/Vision/Dreambox/dm8000/openvision-e2-test-py3.11-13.1-r545-dm8000-20230622_webif.zip

Flash version: https://images.openvision.dedyn.io/13.1/.Test/Vision/Dreambox/dm8000/openvision-e2-test-py3.11-13.1-r545-dm8000-20230622_flash.zip

**Comment by Leeawa12** [comment]
Thank you very much...the old problem..is gone..and a new problem has appeared...the display screen is of

![1](https://github.com/OpenVisionE2/reports/assets/136477333/76a64d3a-146c-480f-bd5f-c1095b2f210a)

**Comment by Leeawa12** [comment]
I'm still waiting....why is there no response

**Comment by Leeawa12** [comment]
How long to wait

**Comment by persianpros** [comment]
We will release a new image this week. Busy with new C++ changes.

**Comment by Leeawa12** [comment]
openvision-e2-develop-py3.11-13.1-r548-dm8000-20230705
Only one problem is the screen does not show the channel name

![٢٠٢٣٠٧٠٥_٢١٤١٥٥](https://github.com/OpenVisionE2/reports/assets/136477333/4a558f6d-8838-43b8-9757-a319881d747f)

**Comment by Leeawa12** [comment]
Another problem...while recording

[enigma2_crash_2023-07-06_03-48-31.log](https://github.com/OpenVisionE2/reports/files/11963070/enigma2_crash_2023-07-06_03-48-31.log)

**Comment by Leeawa12** [comment]
Why is there no response

**Comment by Leeawa12** [comment]
Why is there no response ?????

**Comment by Leeawa12** [comment]
openvision-e2-develop-py3.11-13.1-r549-dm8000-20230715

After downloading the image, it stops on this screen, and the settings cannot be completed

![٢٠٢٣٠٧١٥_٢٣١٩١٠](https://github.com/OpenVisionE2/reports/assets/136477333/1673d423-47ec-4771-812c-26c77ce59618)

I think you're a team fit for pizza only

Fuck you, the device has completely stopped working, but your failed team

A very failed team, I will show you all the forums

**Comment by persianpros** [comment]
Just waited to see the real shit, always works.

Go to hell.

**Comment by persianpros** [comment]
Simply blocked, no time to write shit about you.
